AppGames.App/Models/ErrorViewModel.cs
using System;

namespace AppGames.App.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AppGames.App/Models/Plataforma/PlataformaCadastroViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AppGames.App.Models.Plataforma
{
    public class PlataformaCadastroViewModel
    {
        [Required(ErrorMessage = "Informe o nome da plataforma")]
        public string Nome { get; set; }
    }
}

AppGames.App/Models/Plataforma/PlataformaConsultaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppGames.App.Models.Plataforma
{
    public class PlataformaConsultaViewModel
    {
        public int IdPlataforma { get; set; }
        public string Nome { get; set; }
    }
}

AppGames.App/Models/Plataforma/PlataformaEdicaoViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AppGames.App.Models.Plataforma
{
    public class PlataformaEdicaoViewModel
    {
        [Required(ErrorMessage = "Informe o id da plataforma")]
        public int IdPlataforma { get; set; }

        [Required(ErrorMessage = "Informe o nome da plataforma")]
        public string Nome { get; set; }
    }
}

AppGames.App/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AppGames.Dados.Contracts;
using Microsoft.AspNetCore.Mvc;

namespace AppGames.App.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;

        public GameController(IGameRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

AppGames.App/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using AppGames.App.Models;

namespace AppGames.App.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AppGames.App/Controllers/PlataformaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AppGames.App.Models.Plataforma;
using AppGames.Dados.Contracts;
using AppGames.Entidades;
using Microsoft.AspNetCore.Mvc;

namespace AppGames.App.Controllers
{
    public class PlataformaController : Controller
    {
        private readonly IPlataformaRepository repository;

        public PlataformaController(IPlataformaRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
        public IActionResult Index()
        {
            IList<PlataformaConsultaViewModel> lista = new List<PlataformaConsultaViewModel>();

            foreach(var plataforma in repository.FindAll())
            {
                PlataformaConsultaViewModel model = new PlataformaConsultaViewModel();
                model.IdPlataforma = plataforma.IdPlataforma;
                model.Nome = plataforma.Nome;

                lista.Add(model);
            }

            return View(lista);
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
        public IActionResult Salvar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Salvar(PlataformaCadastroViewModel model)
        {
            if (ModelState.IsValid)
            {
                var plataforma = new Plataforma();

                plataforma.Nome = model.Nome;

                repository.Insert(plataforma);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
        public IActionResult Editar(int id)
        {
            var plataforma = repository.FindById(id);

            var model = new PlataformaEdicaoViewModel();

            model.IdPlataforma = plataforma.IdPlataforma;
            model.Nome = plataforma.Nome;

            return View(model);
        }

        [HttpPost]
        public IActionResult Editar(PlataformaEdicaoViewModel model)
        {
            if (ModelState.IsValid)
            {
                var plataforma = new Plataforma();

                plataforma.IdPlataforma = model.IdPlataforma;
                plataforma.Nome = model.Nome;

                repository.Update(plataforma);

                return RedirectToAction("Index");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public IActionResult Deletar(int id)
        {
            var plataforma = repository.FindById(id);

            repository.Delete(plataforma);

            return RedirectToAction("Index");
        }
    }
}

AppGames.App/Views/Game/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

AppGames.App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AppGames.App/Views/Plataforma/Editar.cshtml
@{
    ViewData["Title"] = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model AppGames.App.Models.Plataforma.PlataformaEdicaoViewModel

<form class="form-horizontal" method="post" asp-controller="Plataforma" asp-action="Editar">
    <input type="hidden" asp-for="IdPlataforma" />

    <div class="form-group">
        <label class="col-md-1 control-lbel" for="Nome">Nome</label>
        <div class="col-md-2">
            <input type="text" class="form form-control" asp-for="Nome" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <input type="submit" value="Editar" class="btn btn-success" />
            @ViewBag.Mensagem
            <a href="/Plataforma/Index" class="btn btn-default">Voltar</a>
        </div>
    </div>
</form>

AppGames.App/Views/Plataforma/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model List<AppGames.App.Models.Plataforma.PlataformaConsultaViewModel>

<a href="/Plataforma/Salvar" class="btn btn-success">Nova Plataforma</a>
<br />
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Nome
                </td>
                <td>
                    <a href="/Plataforma/Editar/@item.IdPlataforma" class="btn btn-warning btn-sm">Editar</a>
                    <a href="/Plataforma/Deletar/@item.IdPlataforma" class="btn btn-danger btn-sm">Excluir</a>
                </td>
            </tr>
        }
    </tbody>
</table>

AppGames.App/Views/Plataforma/Salvar.cshtml
@{
    ViewData["Title"] = "Salvar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model AppGames.App.Models.Plataforma.PlataformaCadastroViewModel

<form class="form-horizontal" method="post" asp-controller="Plataforma" asp-action="Salvar">
    <div class="form-group">
        <label class="col-md-1 control-lbel" for="Nome">Nome</label>
        <div class="col-md-2">
            <input type="text" class="form form-control" asp-for="Nome" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-2">
            <input type="submit" value="Salvar" class="btn btn-success" />
            @ViewBag.Mensagem
            <a href="/Plataforma/Index" class="btn btn-default">Voltar</a>
        </div>
    </div>
</form>

AppGames.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppGames.App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppGames.App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plataforma" asp-action="Index">Plataforma</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Game</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AppGames.App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>